image:
  repository: ghcr.io/nayetdet/voltswitch-api
  tag: latest
  pullPolicy: IfNotPresent

shutdownCommand: ""

secret:
  enabled: false
  name: voltswitch-api

externalSecret:
  enabled: true
  storeName: ""
  refreshInterval: 1h
  remoteKey: voltswitch-api

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
  tls: []
